### ISSUE TITLE
composer outdated reports this project as outdated

### ISSUE THREAD

**Issue by tstoeckler** [drupal-composer/drupal-security-advisories#14]
Because there is a `composer.json` in the master branch, composer thinks that you can update to a newer version if you are on 8.x, for example.

This would be solved, I think, if the `composer.json` were removed from the master branch. It doesn't serve any practical purpose anyway, as far as I can tell...

**Comment by webflo** [comment]
Thanks! I also removed the branch on Packagist. https://packagist.org/packages/drupal-composer/drupal-security-advisories

**Comment by tstoeckler** [comment]
Perfect, it no longer shows no in the output of `composer outdated`. Thanks! :+1:
