### ISSUE TITLE
Forms Steps - Critical - Access bypass - SA-CONTRIB-2019-064

### ISSUE THREAD

**Issue by greasedonkey** [drupal-composer/drupal-security-advisories#18]
Last August there was an SA for the Forms Steps module (https://www.drupal.org/sa-contrib-2019-064).

In our CI pipeline, we tried using version 1.1 of the Forms Steps project with `drush pm:security` in hope to list that a security update was required, but we would not get any results.

I did some investigation with xdebug and I found out that the `drush pm:security` command use the content of this file (https://github.com/drupal-composer/drupal-security-advisories/blob/8.x-v2/composer.json) from this project to compare it against your project installed modules.

From my understanding it should have been in there, but I'm not sure what is the process to get it in and if we can help in anyway?

Thanks!

**Comment by greasedonkey** [comment]
I'm going to guess it's a bug, I have found the module listed in the non v2 version.

https://raw.githubusercontent.com/drupal-composer/drupal-security-advisories/8.x/composer.json

**Comment by weitzman** [comment]
V2 is a different format for expressing compat. There should not be differences in the projects that are included. Ping @webflo

**Comment by webflo** [comment]
Hi, sorry the CI setup was broken. I fixed it today. The last commit on https://github.com/drupal-composer/drupal-security-advisories/tree/8.x-v2 (https://github.com/drupal-composer/drupal-security-advisories/commit/6314849bafa7512179b5f5368eda36c4802726c3) added a bunch of new constraints.

**Comment by webflo** [comment]
forms_steps is one of them.

**Comment by webflo** [comment]
@greasedonkey Please verify. Thanks!

**Comment by greasedonkey** [comment]
@webflo @weitzman It works guys! Thanks for the help and the quick turnaround!

**Comment by leymannx** [comment]
Maybe also add this as answer to your question on DA https://drupal.stackexchange.com/questions/286598/drush-or-drupal-console-command-to-list-modules-with-security-updates.
