### ISSUE TITLE
Drupal core and themes?

### ISSUE THREAD

**Issue by andrewholgate** [drupal-composer/drupal-security-advisories#2]
As far as I can tell from the `composer.json` file, `drupal-security-advisories` only verifies contributes modules and not Drupal core nor themes.

Ideally it would also verify Drupal core and contributed themes but if this is not possible  then it would be useful to document the scope of the tool.

**Comment by webflo** [comment]
``drupal/zen`` is in https://github.com/drupal-composer/drupal-security-advisories/blob/7.x/composer.json. Do you miss a specific theme? Drupal core is definitely missing, it shouldn't be hard to add it.

**Comment by webflo** [comment]
``drupal/drupal`` has been added in https://github.com/drupal-composer/drupal-security-advisories/commit/ffde96415ef3c9f8c712764b0ad45c7cbc145cc2
