### ISSUE TITLE
Create branch for 9.x-v2 and enable it on build-v2 branch

### ISSUE THREAD

**Issue by verbruggenalex** [drupal-composer/drupal-security-advisories#23]
As I understand it, it would be pretty easy to start the 9.x-v2 by copying the 8.x-v2 branch and enabling it on the build-v2 branch build.sh file: https://github.com/drupal-composer/drupal-security-advisories/blob/build-v2/build/build.sh.

Can we get this done?

**Comment by webflo** [comment]
Hi @verbruggenalex,

you can use the Drupal 8 branch for Drupal 9. The data for Drupal 9 is not different from Drupal 8.

**Comment by verbruggenalex** [comment]
Ah, k. Sorry I didn't realize. Thx for letting me know.
