### ISSUE TITLE
8.x-v2 branch is out of date

### ISSUE THREAD

**Issue by Cyberschorsch** [drupal-composer/drupal-security-advisories#27]
The branch which is used for drush pm:security is out-of-date, it does not add Drupal 8.9.17 as conflict

**Comment by Cyberschorsch** [comment]
Is updating the composer.json an automated task or done manually?

**Comment by joe-netcenter** [comment]
Looks like it updated yesterday!

**Comment by bradjones1** [comment]
OK to close?

**Comment by webflo** [comment]
I guess so. The build is automated with Circle CI.
