### ISSUE TITLE
D8 Support

### ISSUE THREAD

**Issue by grasmash** [drupal-composer/drupal-security-advisories#3]
I appears that the 8.x branch of this project simply includes a static composer.json file. Are there plans to build out the 8.x branch to provide dynamic checks for security advisories?

**Comment by webflo** [comment]
Nope it is up to date, updates 15 days ago. https://github.com/drupal-composer/drupal-security-advisories/commit/ff81bfc3cf145319ec97fe6ce350c4b8deba958e

Do you miss a specific security release?

**Comment by grasmash** [comment]
No, I just looked at the repo and saw only the composer.json, and made a bad assumption. I suppose I was expecting to see the script that generates it. I don't quite understand the mechanism that keeps the composer.json file up to date. Perhaps that's the code on the master branch, and an automated process runs on a server somewhere and updates the repo when there's a new release?

**Comment by webflo** [comment]
Master branch contains the build.sh. Its executed by circleci (https://github.com/drupal-composer/drupal-security-advisories/blob/master/circle.yml)

**Comment by webflo** [comment]
Build History: https://circleci.com/gh/drupal-composer/drupal-security-advisories/tree/master
