### ISSUE TITLE
Easy Breadcrumb 1.15 is not supported but not on the list

### ISSUE THREAD

**Issue by mxr576** [drupal-composer/drupal-security-advisories#31]
As of today the list for easy_breadcrumb looks like this https://github.com/drupal-composer/drupal-security-advisories/blob/6a96e7ef3da0583aef70579bb1c9d927928bbeeb/composer.json

But anything below <2.0.0 is not supported according to Drupal.org package and module update UI: https://www.drupal.org/project/easy_breadcrumb
![image](https://user-images.githubusercontent.com/1755573/151512172-470e6083-a18a-42d8-ba55-b95f116a3f0b.png)

**Comment by webflo** [comment]
Thanks, this is related or duplicate of https://github.com/drupal-composer/drupal-security-advisories/issues/29. I'am gone use easy_breadcrumb as an example.
