### ISSUE TITLE
dev-9.-x alias does not exist

### ISSUE THREAD

**Issue by FlorentTorregrosa** [drupal-composer/drupal-security-advisories#32]
Hi,

Seeing Drush releases notes, I have tried to update my requirement in my project composer.json

```
        "drupal-composer/drupal-security-advisories": "dev-9.x",
```

But it ended with:

```
 Problem 1
    - Root composer.json requires drupal-composer/drupal-security-advisories dev-9.x, found drupal-composer/drupal-security-advisories[dev-7.x-v2, dev-8.x-v2, 7.x-dev, 8.x-dev, 9.x-dev] but it does not match the constraint.
```

It seems that there is no dev-9.x alias for this branch.

README needs to be updated.

**Comment by alexseif** [comment]
Yes, I was just in this same issue I think it's been renamed but the documentation wasn't updated
`composer require drupal-composer/drupal-security-advisories:9.x-dev`

**Comment by webflo** [comment]
Fixed. Thanks!
