### ISSUE TITLE
Latest security releases are missing

### ISSUE THREAD

**Issue by Bladedu** [drupal-composer/drupal-security-advisories#42]
I notice that the latest security release from yesterday hasn't popped up yet.

I did also notice that Drupal is one fix release behind and that the whole 10 branch is missing from tracking.

Are there any plans for maintaining the Drupa l10 version with this tool?

**Comment by pameeela** [comment]
Per https://github.com/drush-ops/drush/issues/4007 this should auto-update via CircleCI. But I am guessing that because of the hack late last year, the key has to be updated.

**Comment by jcnventura** [comment]
This has now been fixed. Thanks @webflo

**Comment by webflo** [comment]
@pameeela was correct, the pipeline trigger was invalid due an invalid key. I reconfigured the trigger (cronjob) on Circle CI.

![image](https://user-images.githubusercontent.com/123946/214245922-7c2bdd9b-8883-4360-b258-afd275ffda4d.png)
