### ISSUE TITLE
Explicit License

### ISSUE THREAD

**Issue by grota** [drupal-composer/drupal-security-advisories#43]
Hi @webflo @weitzman @drumm
we recently forked this repo under our org, in an attempt to:

- manage on our end the code contributions (we liked [tuutti's recent contribution](https://github.com/drupal-composer/drupal-security-advisories/pull/41))
- have a "backup strategy" to generate the resulting composer.json with the SA conflicts.

We have found no mention of the license in the code (only in the [generated artifact](https://github.com/drupal-composer/drupal-security-advisories/blob/aa3f4a4796714244aea027e32f8ff8bed8856eb3/composer.json#L5)).
We were wondering if you could make this project's license explicit as open source in order to avoid any legal issue by forking and using this project in our org.

**Comment by webflo** [comment]
I have little experience how to choose the right license :/ . Its GPL-2.0-or-later ok for everyone? Same as the generated files. I removed the file in commit c88123b82c89a04a6253ddc997c193bddf6b010e so it wouldn't show up in Packagist. It was not intended to remove the license.

**Comment by grota** [comment]
:)  I/we are not lawyers either, GPL-2.0-or-later is ok for us.
https://choosealicense.com/licenses/gpl-2.0/
https://spdx.org/licenses/GPL-2.0-or-later.html
Yeah I understand the removal of the top level composer.json, I'll try to create a PR with the [facilities provided by github](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

**Comment by grota** [comment]
done in #44, the initial header I took from https://github.com/Automattic/jetpack/pull/7879/files
