### ISSUE TITLE
Create a drupal.org compatible version.

### ISSUE THREAD

**Issue by mickaelperrin** [drupal-composer/drupal-security-advisories#5]
Hi,

As spotted by you, currently the generated composer file uses the version scheme from  https://packagist.drupal-composer.org/ and not from drupal.org.

It causes issues when using drupal-composer/drupal-security-advisories with 

    "repositories": [
    {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
    }
    ],

For example, the constraint on `editor_file` is set to `<8.1.2` instead of `1.2`.

Thx,

**Comment by Jaesin** [comment]
https://github.com/drupal-composer/drupal-security-advisories/pull/4

**Comment by webflo** [comment]
- I moved the old package to https://packagist.org/packages/drupal-composer/drupal-security-advisories-legacy. 
- Got rid of the drupal-parse-composer because the new version scheme is very simple
- Renamed 8.0.x to 8.x
